### ISSUE TITLE
Contribution with new CircleCI config process hook

### ISSUE THREAD

**Issue by JulienWeintraub** [zahorniak/pre-commit-circleci#14]
Hello,

I started to prepare a PR to bring the `circleci config process` hook, next to the validate one.

I noticed I don't have write permissions to push my branch, is there a way allowing me to contribute to that project ?

Thanks :)

**Comment by zahorniak** [comment]
Hi @JulienWeintraub. If I understand you correctly, you can fork this repo, make your changes, and then create a PR to it. This should work.

**Comment by JulienWeintraub** [comment]
@zahorniak done in https://github.com/zahorniak/pre-commit-circleci/pull/15 ;)

**Comment by zahorniak** [comment]
This PR is included in version 1.2.0 :tada:

**Comment by JulienWeintraub** [comment]
Just tested, for the result : 
```sh
Circleci config.yml config validate......................................Passed
Circleci generated_config.yml config validate............................Passed
Circleci config files processing (on-demand).............................Passed
Circleci config files processing (scheduled).............................Passed
```

With : 
```yaml
  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v1.2.0
    hooks:
      - id: circleci_validate
        name: Circleci config.yml config validate
        args:
          - --org-slug=***
          - .circleci/config.yml
      - id: circleci_validate
        name: Circleci generated_config.yml config validate
        args:
          - --org-slug=***
          - .circleci/generated_config.yml
      - id: circleci_process
        name: Circleci config files processing (on-demand)
        args:
          - --org-slug=***
          - '--pipeline-parameters {"build-type": "on-demand"}'
          - .circleci/config.yml .circleci/generated_config.yml
      - id: circleci_process
        name: Circleci config files processing (scheduled)
        args:
          - --org-slug=***
          - '--pipeline-parameters {"build-type": "scheduled"}'
          - .circleci/config.yml .circleci/generated_config.yml
```
